# AhliAnak App Flow Document

## Onboarding and Sign-In/Sign-Up

When Indonesian mothers first download the AhliAnak mobile application, they are welcomed by a series of 3-5 elegant onboarding screens that concisely explain the app's purpose as a voice-first pediatric consultation platform. These screens introduce the key features—voice-to-text consultations, asynchronous pediatrician responses, and child health profile management—all presented in a clean, reassuring interface with culturally appropriate visuals. The sign-up process offers both email/password registration and a streamlined Gmail option for quick account creation without lengthy forms. After successful authentication, first-time users are guided to complete a minimal profile with just their name, keeping the onboarding process light while ensuring personalization. The app's security is reinforced with clear logout options, a straightforward "Forgot Password" feature with email verification, and helpful error messages for incorrect login attempts—all designed with the busy Indonesian mom in mind. Once basic profile information is collected, users are directed to create their first child's profile, transitioning seamlessly to the dashboard that will become their command center for health management.

## Main Dashboard or Home Page (Beranda Tab)

After authentication, users land on the Beranda (Dashboard) tab—the heart of the AhliAnak experience. The dashboard presents a personalized and intuitive interface with a clean, mobile-native design organized into distinct sections. At the top, child avatars provide quick access to each child's profile, while below, a consultation widget prominently displays 1-2 recent or active consultations with clear status indicators (Active, Awaiting Response, Completed). For moms without active consultations, helpful guidance prompts appear with clear next steps. The dashboard also features age-personalized blog articles and FAQs tailored to each child's developmental stage—when a mom has one child aged 1-2 years, she'll see relevant articles for that age group; with multiple children, she'll see content customized for each child's age in a side-overlap scrollable view. A prominent "Start New Consultation" button provides instant access to begin the doctor selection process. Navigation throughout the app is handled by a consistent bottom navbar with five clearly labeled tabs: Beranda (Dashboard), Anak (Children Profiles), Ahli (Doctor Discovery), Riwayat (Consultation History), and Profil (User Profile & Settings).

## Detailed Feature Flows and Page Transitions

The journey through AhliAnak follows intuitive, purpose-driven flows optimized for Indonesian mothers' needs. When starting a new consultation from the dashboard, users are directed to the Ahli tab where they can select a pediatrician based on specialty, proximity, and availability. After doctor selection, users complete payment via Flip.id integration, choosing between two clear packages (Rp 50,000 unlimited or Rp 20,000 limited topic), with optional promotional code entry for discounts. Post-payment, users specify whether their question relates to a specific child (selecting which one) or general parenting advice. The voice-first interface then enables moms to record their health concerns naturally, which the AI intelligently transcribes and structures with emotional urgency tagging. The system automatically generates clarification questions to ensure comprehensive context before submission, and moms can manually edit the summary if needed before sending to their selected pediatrician.

When a pediatrician responds, the mom receives a notification and can view the async chat with markdown-rendered messages clearly labeled as "Doctor Clarification" or "Final Answer." The doctor's voice responses are transformed into structured text summaries by AI, maintaining the voice-first approach while ensuring information clarity. For completed consultations, a "Restart Session" button on both the dashboard and in the history view allows moms to quickly initiate a new paid consultation with the same doctor (if available) or redirects them to select a different doctor if the original one is unavailable.

Within each child's profile, accessible via the Anak tab or dashboard avatars, moms can view and edit child information (age, allergies, medical history) and see a dedicated consultation timeline specific to that child—creating a focused health history for each child separately. The Riwayat (History) tab provides a consolidated view of all consultations across children with keyword search functionality, allowing moms to quickly locate specific health discussions. Throughout these transitions, the app maintains contextual relevance, with navigation paths that intuitively connect related features while preserving the mom's place in her workflow.

## Settings and Account Management

The Profil tab serves as the gateway to comprehensive account management and settings. Here, mothers can edit their personal information, manage notification preferences for doctor replies and consultation updates, and modify language preferences with a clear switch between Bahasa Indonesia (default) and other supported languages. The app allows mothers to view their transaction history with downloadable receipts for each consultation, manage their payment methods, and input promotional codes for future discounts. Security settings provide options to change passwords, update email addresses, and manage Gmail connection status. Throughout the profile section, the interface maintains the app's overall clean and intuitive design, with clearly labeled sections and simple toggle controls for various settings. After making changes, users can easily return to their previous workflow via the bottom navbar or through contextual back buttons, ensuring a seamless transition between account management and the app's core health consultation features.

## Error States and Alternate Paths

AhliAnak is engineered to handle unexpected situations gracefully, ensuring mothers remain confident even when things don't go as planned. If a network connection fails during payment processing with Flip.id, the system preserves the consultation state and allows retry once connectivity is restored. When moms encounter microphone access issues while recording voice notes, a text input alternative automatically appears, maintaining the consultation flow without forcing app restart. For scenarios where AI processing encounters difficulties with transcription (due to background noise or unclear speech), clear error messages prompt users to re-record with feedback for better results. If the selected doctor becomes unavailable after a mom attempts to restart a session, a notification clearly explains the situation and smoothly redirects her to the Ahli tab to select an alternative pediatrician. When child profile images fail to load, the system displays a default avatar with the child's initials. Throughout these alternate paths, the app maintains context awareness—if a consultation history fails to load in the Riwayat tab, users see an appropriate error message with retry options while still being able to navigate to other sections of the app. This comprehensive error handling creates trust in the platform, particularly important for health-related concerns where reliability is paramount.

## Conclusion and Overall App Journey

The AhliAnak journey is meticulously designed for Indonesian mothers seeking pediatric health guidance. Starting with a streamlined onboarding and authentication process, mothers quickly establish their identity and create profiles for their children with essential health information. The Beranda dashboard serves as the central command post, offering immediate access to ongoing consultations, child profiles, and age-relevant content. When health concerns arise, the voice-first consultation process transforms spoken questions into structured summaries, with AI-driven follow-up questions ensuring comprehensive context for pediatricians. The asynchronous communication model respects both the mother's busy schedule and the doctor's need for thoughtful response time, while maintaining clear status indicators throughout the process. Child profiles evolve into valuable health timelines, creating a chronological record of consultations specific to each child. Throughout the experience, the app's five-tab navigation system (Beranda, Anak, Ahli, Riwayat, Profil) provides consistent orientation, while robust error handling maintains user confidence even when technical challenges occur. By combining voice technology, AI-structured summaries, and certified pediatrician expertise, AhliAnak creates a supportive environment where Indonesian mothers can become more confident, informed, and proactive in managing their children's health—transforming traditional medical consultation into an accessible, mobile-native experience aligned with modern motherhood. 